suite: test deployment
templates:
  - templates/pvc.yaml
  - templates/deployment.yaml
tests:
  - it: persistence is enabled
    template: pvc.yaml
    set:
      persistence:
        enabled: true
        create: true
    asserts:
      - hasDocuments:
          count: 1
      - isKind:
          of: PersistentVolumeClaim
      - equal:
          path: spec.accessModes[0]
          value: "ReadWriteOnce"
  - it: persistence is enabled but pvc is not created
    template: pvc.yaml
    set:
      persistence:
        enabled: true
        create: false
    asserts:
      - hasDocuments:
          count: 0

  - it: persistence is enabled but pvc is not created
    template: templates/deployment.yaml
    set:
      persistence:
        enabled: true
        create: true
    asserts:
      - hasDocuments:
          count: 1
      - equal:
          path: spec.template.spec.containers[0].volumeMounts
          value:
            - mountPath: /etc/woodpecker/agent.config
              name: agent-config
              subPath: agent.config
