suite: test deployment
templates:
  - templates/statefulset.yaml
tests:
  - it: persistentVolume enabled
    set:
      persistentVolume:
        enabled: true
    asserts:
      - equal:
          path: spec.volumeClaimTemplates[0].spec.accessModes[0]
          value: 'ReadWriteOnce'
  - it: persistentVolume enabled with one accessModes
    set:
      persistentVolume:
        enabled: true
        accessModes:
          - 'ReadWriteOncePod'
    asserts:
      - equal:
          path: spec.volumeClaimTemplates[0].spec.accessModes[0]
          value: 'ReadWriteOncePod'
  - it: persistentVolume enabled with two accessModes
    set:
      persistentVolume:
        enabled: true
        accessModes:
          - 'ReadWriteOncePod'
          - 'ReadWriteMany'
    asserts:
      - equal:
          path: spec.volumeClaimTemplates[0].spec.accessModes[0]
          value: 'ReadWriteOncePod'
      - equal:
          path: spec.volumeClaimTemplates[0].spec.accessModes[1]
          value: 'ReadWriteMany'
  - it: persistentVolume enabled with one label
    set:
      persistentVolume:
        enabled: true
        labels:
          - 'label0'
    asserts:
      - equal:
          path: spec.volumeClaimTemplates[0].metadata.labels[0]
          value: 'label0'
  - it: persistentVolume enabled with two labels
    set:
      persistentVolume:
        enabled: true
        labels:
          - 'label0'
          - 'label1'
    asserts:
      - equal:
          path: spec.volumeClaimTemplates[0].metadata.labels[0]
          value: 'label0'
      - equal:
          path: spec.volumeClaimTemplates[0].metadata.labels[1]
          value: 'label1'
  - it: persistentVolume enabled with one annotation
    set:
      persistentVolume:
        enabled: true
        annotations:
          - 'annotation0'
    asserts:
      - equal:
          path: spec.volumeClaimTemplates[0].metadata.annotations[0]
          value: 'annotation0'
  - it: persistentVolume enabled with two annotations
    set:
      persistentVolume:
        enabled: true
        annotations:
          - 'annotation0'
          - 'annotation1'
    asserts:
      - equal:
          path: spec.volumeClaimTemplates[0].metadata.annotations[0]
          value: 'annotation0'
      - equal:
          path: spec.volumeClaimTemplates[0].metadata.annotations[1]
          value: 'annotation1'
  - it: persistentVolume enabled with existingClaim
    set:
      persistentVolume:
        enabled: true
        existingClaim: 'my-claim'
    asserts:
      - notExists:
          path: spec.volumeClaimTemplates[0].spec.accessModes[0]
      - equal:
          path: spec.template.spec.volumes
          value:
            - name: agent-config
              persistentVolumeClaim:
                claimName: my-claim
  - it: persistentVolume disabled
    set:
      persistentVolume:
        enabled: false
    asserts:
      - notExists:
          path: spec.template.spec.volumes
      - notExists:
          path: spec.template.spec.containers[0].volumeMounts
          value:
            - mountPath: /data
              name: data
      - notExists:
          path: spec.volumeClaimTemplates
