# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
suite: topologySpreadConstraints template
release:
  name: woodpecker-unittests
  namespace: testing
templates:
  - templates/statefulset.yaml
tests:
  - it: renders topologySpreadConstraints when set
    capabilities:
      majorVersion: 1
      minorVersion: 25
    set:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: woodpecker-server
    asserts:
      - hasDocuments:
          count: 1
      - equal:
          path: spec.template.spec.topologySpreadConstraints
          value:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: woodpecker-server
  - it: omits topologySpreadConstraints by default
    capabilities:
      majorVersion: 1
      minorVersion: 25
    asserts:
      - hasDocuments:
          count: 1
      - notExists:
          path: spec.template.spec.topologySpreadConstraints
  - it: omits topologySpreadConstraints on Kubernetes below 1.19
    capabilities:
      majorVersion: 1
      minorVersion: 18
    set:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
    asserts:
      - hasDocuments:
          count: 1
      - notExists:
          path: spec.template.spec.topologySpreadConstraints
