variables:
  - &helm_image alpine/helm:latest

pipeline:
  set-version:
    image: *helm_image
    commands:
      # use tag name or 0.0.0 if not running on a tag
      - export CHART_VERSION="${CI_COMMIT_TAG##v}"
      - export CHART_VERSION=$${CHART_VERSION:=0.0.0}
      - echo "Version $CHART_VERSION"
      - sed -i "s/<version>/$CHART_VERSION/g" woodpecker-agent/Chart.yaml
      - sed -i "s/<version>/$CHART_VERSION/g" woodpecker-server/Chart.yaml
      - cat woodpecker-agent/Chart.yaml
      - cat woodpecker-server/Chart.yaml

  lint:
    image: *helm_image
    commands:
      - helm lint woodpecker-agent/
      - helm lint woodpecker-server/

  release:
    image: quay.io/helmpack/chart-releaser:v1.5.0
    secrets:
      - source: github_token
        target: CR_TOKEN
    commands:
      - git config --global user.email "woodpecker-bot@obermui.de"
      - git config --global user.name "woodpecker-bot"
      - mkdir -p .cr-index
      - cr package woodpecker-server
      - cr package woodpecker-agent
      - cr upload --owner woodpecker-ci --git-repo woodpecker-ci.github.io --release-name-template "helm-{{ .Name }}-{{ .Version }}"
      - git clone https://github.com/woodpecker-ci/woodpecker-ci.github.io.git
      - cd woodpecker-ci.github.io/ && cr index --owner woodpecker-ci --git-repo woodpecker-ci.github.io --pages-branch master --package-path ../.cr-release-packages --index-path ../.cr-index/index.yaml --charts-repo https://woodpecker-ci.org --push --release-name-template "helm-{{ .Name }}-{{ .Version }}"
    when:
      event: tag
