variables:
  - &helm_image alpine/helm:latest

when:
  - event: tag
  - event: push
    branch: main
  - event: pull_request

pipeline:
  lint:
    image: *helm_image
    commands:
      - helm lint --with-subcharts

  update-readme:
    image: jnorwood/helm-docs:v1.11.0
    commands:
      - helm-docs -t README.md.gotmpl
    when:
      - event: tag

  push-updated-readme:
    image: appleboy/drone-git-push
    settings:
      branch: main
      commit: true
      ssh_key:
        from_secret: BOT_PRIVATE_KEY
      commit_message: "[skip ci] Update README.md"
   when:
      - event: tag   

  release:
    image: quay.io/helmpack/chart-releaser:v1.5.0
    secrets:
      - source: github_token
        target: CR_TOKEN
    commands:
      - git config --global user.email "woodpecker-bot@obermui.de"
      - git config --global user.name "woodpecker-bot"
      - mkdir -p .cr-index
      - cr package .
      - cr upload --owner woodpecker-ci --git-repo woodpecker-ci.github.io --release-name-template "helm-{{ .Name }}-{{ .Version }}"
      - git clone https://github.com/woodpecker-ci/woodpecker-ci.github.io.git
      - cd woodpecker-ci.github.io/ && cr index --owner woodpecker-ci --git-repo woodpecker-ci.github.io --pages-branch master --package-path ../.cr-release-packages --index-path ../.cr-index/index.yaml --charts-repo https://woodpecker-ci.org --push --release-name-template "helm-{{ .Name }}-{{ .Version }}"
    when:
      - event: tag
