{{- if .Values.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
  namespace: {{ .namespace }}
type: Opaque
{{- end }}

---
apiVersion: batch/v1
kind: Job
metadata:
  name: pre-install-agent-secret-check
  annotations:
    "helm.sh/hook": pre-install
spec:
  template:
    spec:
      containers:
      - name: check-agent-secret
        image: finalgene/openssh:9
        command: ["openssl"]
        args: ["rand", "-hex", "32"]
      restartPolicy: OnFailure
