{{- if .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "woodpecker-server.fullname" . }}
  labels:
    {{- include "woodpecker-server.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
    {{- include "woodpecker-server.selectorLabels" . | nindent 6 }}
  podMetricsEndpoints:
  - port: metrics
    interval: {{ .Values.metrics.interval }}
    path: {{ .Values.metrics.path }}
{{- end }}
