apiVersion: v2
name: server
description: A Helm chart for the Woodpecker server
type: application
version: 0.1.0
appVersion: "v0.15.7"
keywords:
  - continuous-delivery
  - continuous-deployment
  - continuous-integration
  - docker
  - go
sources:
  - https://github.com/woodpecker-ci/woodpecker
maintainers:
  - name: Woodpecker Maintainers
    email: owner@woodpecker-ci.org
