when:
  - event: tag
  - event: push
    branch: main
  - event: pull_request

steps:
  lint-markdown:
    depends_on: []
    image: docker.io/davidanson/markdownlint-cli2:v0.18.1
    commands:
      - 'markdownlint-cli2 *.{md,markdown}'

  editor-config:
    image: docker.io/woodpeckerci/plugin-editorconfig-checker:0.3.2
    depends_on: []

  helm-lint:
    image: docker.io/alpine/helm:3.19.0
    depends_on: []
    commands:
      - helm dependency update charts/woodpecker
      - helm lint --with-subcharts charts/*

  lint-yaml:
    image: docker.io/pipelinecomponents/yamllint:0.35.6
    depends_on: []
    commands:
      - yamllint .
    when:
      path: '*.{yml,yaml}'

  lint-prettier:
    image: docker.io/woodpeckerci/plugin-prettier:1.4.0
    depends_on: []
    settings:
      version: 3.3.3
