when:
  - event: tag
  - event: push
    branch: main
  - event: pull_request

steps:
  lint-markdown:
    depends_on: []
    image: docker.io/davidanson/markdownlint-cli2:v0.18.1
    commands:
      - 'markdownlint-cli2 *.{md,markdown}'

  editor-config:
    image: docker.io/mstruebing/editorconfig-checker:v3.3.0
    depends_on: []
    commands:
      - ec --config .editorconfig-checker.json .

  helm-lint:
    image: docker.io/alpine/helm:3.17.3
    depends_on: []
    commands:
      - helm dependency update charts/woodpecker
      - helm lint --with-subcharts charts/*

  lint-yaml:
    image: docker.io/pipelinecomponents/yamllint:0.34.0
    depends_on: []
    commands:
      - yamllint .
    when:
      path: '*.{yml,yaml}'

  lint-prettier:
    image: docker.io/woodpeckerci/plugin-prettier:1.3.0
    depends_on: []
    settings:
      version: 3.3.3
