depends_on:
  - test

when:
  - event: tag
  - event: pull_request

steps:
  pack-chart:
    image: quay.io/helmpack/chart-releaser:v1.5.0
    commands:
      - mkdir -p .cr-index
      - cr package charts/woodpecker

  release-chart:
    image: quay.io/helmpack/chart-releaser:v1.5.0
    secrets:
      - source: github_token
        target: CR_TOKEN
    commands:
      - git config --global user.email "woodpecker-bot@obermui.de"
      - git config --global user.name "woodpecker-bot"
      - cr upload --skip-existing --owner woodpecker-ci --git-repo woodpecker-ci.github.io --release-name-template "helm-{{ .Name }}-{{ .Version }}"
      - git clone https://github.com/woodpecker-ci/woodpecker-ci.github.io.git
      - cd woodpecker-ci.github.io/
      - cr index --owner woodpecker-ci --git-repo woodpecker-ci.github.io --pages-branch master --package-path ../.cr-release-packages --index-path ../.cr-index/index.yaml --push --release-name-template "helm-{{ .Name }}-{{ .Version }}"
      - cd ..
      - rm -rf woodpecker-ci.github.io/
      - git reset --hard
    when:
      - event: tag

  release-oci:
    image: alpine/helm:3.13.1
    secrets: [dockerhub_token]
    commands:
      - helm package . --version ${CI_COMMIT_TAG}
      - echo $${DOCKERHUB_TOKEN} | helm registry login -u woodpeckerbot registry-1.docker.io --password-stdin
      - helm push woodpecker-${CI_COMMIT_TAG}.tgz oci://registry-1.docker.io/woodpeckerci/helm
      - helm registry logout registry-1.docker.io
    when:
      - event: tag

  update-readme:
    image: jnorwood/helm-docs:v1.11.3
    commands:
      - helm-docs
      - helm-docs -t README-main.md.gotmpl -g .
      - cat README.md

  push-readme:
    image: appleboy/drone-git-push:1.0.5
    settings:
      remote: ssh://git@github.com/woodpecker-ci/helm.git
      branch: main
      commit: true
      ssh_key:
        from_secret: BOT_PRIVATE_KEY
      commit_message: "[skip ci] Update README.md"
    when:
      - event: tag
