when:
  event: push
  branch: ${CI_REPO_DEFAULT_BRANCH}

steps:
  release-helper:
    image: docker.io/woodpeckerci/plugin-ready-release-go:3.2.0
    pull: true
    settings:
      release_branch: ${CI_REPO_DEFAULT_BRANCH}
      forge_type: github
      git_email: woodpecker-bot@obermui.de
      github_token:
        from_secret: GITHUB_TOKEN
