when:
  - event: tag
  - event: push
    branch: main
  - event: pull_request

steps:
  lint:
    image: alpine/helm:3.13.1
    commands:
      - helm lint --with-subcharts

  test-chart:
    image: quay.io/helmpack/chart-testing:v3.10.0
    commands:
      # Needed for `ct` to check which chart was edited. See https://github.com/woodpecker-ci/helm/pull/56#issuecomment-1676343140
      - git fetch origin main --unshallow --no-tags || true
      - git fetch origin main --no-tags || true
      - git branch main origin/main || true
      - ct list-changed --config ct.yaml
      - ct lint --config ct.yaml
