when:
  - event: tag
  - event: push
    branch: main
  - event: pull_request

steps:
  - name: lint
    image: docker.io/alpine/helm:4.0.1
    commands:
      - helm lint --with-subcharts charts/*

  - name: unittest
    image: docker.io/alpine/helm:4.0.1
    environment:
      # renovate: datasource=github-releases depName=helm-unittest/helm-unittest
      HELM_UNITTEST_VERSION: v1.0.3
    commands:
      - helm plugin install --verify=false --version $HELM_UNITTEST_VERSION https://github.com/helm-unittest/helm-unittest > /dev/null
      - helm unittest --strict -f 'unittests/**/*.yaml' ./charts/woodpecker/charts/server/ ./charts/woodpecker/charts/agent

  - name: test-chart
    image: quay.io/helmpack/chart-testing:v3.14.0
    commands:
      # Needed for `ct` to check which chart was edited. See https://github.com/woodpecker-ci/helm/pull/56#issuecomment-1676343140
      - git fetch origin main --unshallow --no-tags || true
      - git fetch origin main --no-tags || true
      - git branch main origin/main || true
      - ct list-changed --config ct.yaml
      - ct lint --config ct.yaml
