when:
  - event: tag
  - event: push
    branch: main
  - event: pull_request

steps:
  lint:
    image: go-alpine
    commands:
      - apk add --no-cache git helm
      - helm lint --with-subcharts
      ### helm-docs
      # until v1.11.1 is released
      - git clone https://github.com/norwoodj/helm-docs.git --depth 1
      - cd cmd/helm-docs && go build
      - mv helm-docs /usr/local/bin/
      - helm-docs -x

  test-chart:
    image: quay.io/helmpack/chart-testing
    commands:
      # Needed for `ct` to check which chart was edited. See https://github.com/woodpecker-ci/helm/pull/56#issuecomment-1676343140
      - git fetch origin main --unshallow --no-tags || true
      - git branch main origin/main || true
      - ct list-changed --config ct.yaml
      - ct lint --config ct.yaml
