when:
  - event: tag
  - event: push
    branch: main
  - event: pull_request

steps:
  lint:
    image: alpine/helm:3.13.2
    commands:
      - helm lint --with-subcharts

  unittest:
    image: alpine/helm:3.13.2
    environment:
      # NB: we can't use the official helmunittest/helm-unittest image as it's rootless and WP does not support that
      # renovate: datasource=github-releases depName=helm-unittest/helm-unittest
      - HELM_UNITTEST_VERSION=v0.3.6
    commands:
      - helm plugin install --version $HELM_UNITTEST_VERSION https://github.com/helm-unittest/helm-unittest > /dev/null
      - helm unittest --strict -f 'unittests/**/*.yaml' ./charts/server/

  test-chart:
    image: quay.io/helmpack/chart-testing:v3.10.1
    commands:
      # Needed for `ct` to check which chart was edited. See https://github.com/woodpecker-ci/helm/pull/56#issuecomment-1676343140
      - git fetch origin main --unshallow --no-tags || true
      - git fetch origin main --no-tags || true
      - git branch main origin/main || true
      - ct list-changed --config ct.yaml
      - ct lint --config ct.yaml
